apiVersion: v1
kind: Service
metadata:
  name: buy-flower-admin-fe
  namespace: buy-flower-staging
spec:
  selector:
    app: buy-flower-admin-fe
  ports:
    - port: 81
      targetPort: 80
      nodePort: 30005
  type: NodePort